// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: pkg/api/location.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationService_UpdateLocation_FullMethodName     = "/api.LocationService/UpdateLocation"
	LocationService_GetDriversInRadius_FullMethodName = "/api.LocationService/GetDriversInRadius"
	LocationService_GoOnline_FullMethodName           = "/api.LocationService/GoOnline"
	LocationService_GoOffline_FullMethodName          = "/api.LocationService/GoOffline"
)

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationServiceClient interface {
	// Bi-directional stream for real-time location updates
	UpdateLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationUpdate, LocationResponse], error)
	// Query drivers in a specific radius
	GetDriversInRadius(ctx context.Context, in *RadiusQuery, opts ...grpc.CallOption) (*DriverList, error)
	// Driver status management
	GoOnline(ctx context.Context, in *DriverStatusRequest, opts ...grpc.CallOption) (*LocationResponse, error)
	GoOffline(ctx context.Context, in *DriverStatusRequest, opts ...grpc.CallOption) (*LocationResponse, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) UpdateLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationUpdate, LocationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocationService_ServiceDesc.Streams[0], LocationService_UpdateLocation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationUpdate, LocationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationService_UpdateLocationClient = grpc.ClientStreamingClient[LocationUpdate, LocationResponse]

func (c *locationServiceClient) GetDriversInRadius(ctx context.Context, in *RadiusQuery, opts ...grpc.CallOption) (*DriverList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverList)
	err := c.cc.Invoke(ctx, LocationService_GetDriversInRadius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GoOnline(ctx context.Context, in *DriverStatusRequest, opts ...grpc.CallOption) (*LocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, LocationService_GoOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GoOffline(ctx context.Context, in *DriverStatusRequest, opts ...grpc.CallOption) (*LocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, LocationService_GoOffline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility.
type LocationServiceServer interface {
	// Bi-directional stream for real-time location updates
	UpdateLocation(grpc.ClientStreamingServer[LocationUpdate, LocationResponse]) error
	// Query drivers in a specific radius
	GetDriversInRadius(context.Context, *RadiusQuery) (*DriverList, error)
	// Driver status management
	GoOnline(context.Context, *DriverStatusRequest) (*LocationResponse, error)
	GoOffline(context.Context, *DriverStatusRequest) (*LocationResponse, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationServiceServer struct{}

func (UnimplementedLocationServiceServer) UpdateLocation(grpc.ClientStreamingServer[LocationUpdate, LocationResponse]) error {
	return status.Error(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (UnimplementedLocationServiceServer) GetDriversInRadius(context.Context, *RadiusQuery) (*DriverList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriversInRadius not implemented")
}
func (UnimplementedLocationServiceServer) GoOnline(context.Context, *DriverStatusRequest) (*LocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoOnline not implemented")
}
func (UnimplementedLocationServiceServer) GoOffline(context.Context, *DriverStatusRequest) (*LocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoOffline not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}
func (UnimplementedLocationServiceServer) testEmbeddedByValue()                         {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_UpdateLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocationServiceServer).UpdateLocation(&grpc.GenericServerStream[LocationUpdate, LocationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationService_UpdateLocationServer = grpc.ClientStreamingServer[LocationUpdate, LocationResponse]

func _LocationService_GetDriversInRadius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RadiusQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetDriversInRadius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetDriversInRadius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetDriversInRadius(ctx, req.(*RadiusQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GoOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GoOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GoOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GoOnline(ctx, req.(*DriverStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GoOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GoOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GoOffline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GoOffline(ctx, req.(*DriverStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDriversInRadius",
			Handler:    _LocationService_GetDriversInRadius_Handler,
		},
		{
			MethodName: "GoOnline",
			Handler:    _LocationService_GoOnline_Handler,
		},
		{
			MethodName: "GoOffline",
			Handler:    _LocationService_GoOffline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateLocation",
			Handler:       _LocationService_UpdateLocation_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/api/location.proto",
}
