// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/api/order.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNKNOWN    OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING    OrderStatus = 1 // Searching for driver
	OrderStatus_ORDER_STATUS_MATCHED    OrderStatus = 2 // Driver found and assigned
	OrderStatus_ORDER_STATUS_PICKING_UP OrderStatus = 3 // Driver moving to pickup location
	OrderStatus_ORDER_STATUS_PICKED_UP  OrderStatus = 4 // Item picked up
	OrderStatus_ORDER_STATUS_IN_TRANSIT OrderStatus = 5 // Moving to delivery location
	OrderStatus_ORDER_STATUS_DELIVERED  OrderStatus = 6 // Completed
	OrderStatus_ORDER_STATUS_CANCELLED  OrderStatus = 7 // Aborted
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNKNOWN",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_MATCHED",
		3: "ORDER_STATUS_PICKING_UP",
		4: "ORDER_STATUS_PICKED_UP",
		5: "ORDER_STATUS_IN_TRANSIT",
		6: "ORDER_STATUS_DELIVERED",
		7: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNKNOWN":    0,
		"ORDER_STATUS_PENDING":    1,
		"ORDER_STATUS_MATCHED":    2,
		"ORDER_STATUS_PICKING_UP": 3,
		"ORDER_STATUS_PICKED_UP":  4,
		"ORDER_STATUS_IN_TRANSIT": 5,
		"ORDER_STATUS_DELIVERED":  6,
		"ORDER_STATUS_CANCELLED":  7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_order_proto_rawDescGZIP(), []int{0}
}

type DriverOrderActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOrderActionRequest) Reset() {
	*x = DriverOrderActionRequest{}
	mi := &file_pkg_api_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOrderActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOrderActionRequest) ProtoMessage() {}

func (x *DriverOrderActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOrderActionRequest.ProtoReflect.Descriptor instead.
func (*DriverOrderActionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_proto_rawDescGZIP(), []int{0}
}

func (x *DriverOrderActionRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DriverOrderActionRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type Order struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderId             string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId          string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	DriverId            string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	PickupLatitude      float64                `protobuf:"fixed64,4,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	PickupLongitude     float64                `protobuf:"fixed64,5,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	DeliveryLatitude    float64                `protobuf:"fixed64,6,opt,name=delivery_latitude,json=deliveryLatitude,proto3" json:"delivery_latitude,omitempty"`
	DeliveryLongitude   float64                `protobuf:"fixed64,7,opt,name=delivery_longitude,json=deliveryLongitude,proto3" json:"delivery_longitude,omitempty"`
	Status              OrderStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=api.OrderStatus" json:"status,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EstimatedEtaSeconds float64                `protobuf:"fixed64,11,opt,name=estimated_eta_seconds,json=estimatedEtaSeconds,proto3" json:"estimated_eta_seconds,omitempty"`
	Price               float64                `protobuf:"fixed64,12,opt,name=price,proto3" json:"price,omitempty"`
	CurrentLatitude     float64                `protobuf:"fixed64,13,opt,name=current_latitude,json=currentLatitude,proto3" json:"current_latitude,omitempty"`
	CurrentLongitude    float64                `protobuf:"fixed64,14,opt,name=current_longitude,json=currentLongitude,proto3" json:"current_longitude,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_pkg_api_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Order) GetPickupLatitude() float64 {
	if x != nil {
		return x.PickupLatitude
	}
	return 0
}

func (x *Order) GetPickupLongitude() float64 {
	if x != nil {
		return x.PickupLongitude
	}
	return 0
}

func (x *Order) GetDeliveryLatitude() float64 {
	if x != nil {
		return x.DeliveryLatitude
	}
	return 0
}

func (x *Order) GetDeliveryLongitude() float64 {
	if x != nil {
		return x.DeliveryLongitude
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNKNOWN
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Order) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Order) GetEstimatedEtaSeconds() float64 {
	if x != nil {
		return x.EstimatedEtaSeconds
	}
	return 0
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetCurrentLatitude() float64 {
	if x != nil {
		return x.CurrentLatitude
	}
	return 0
}

func (x *Order) GetCurrentLongitude() float64 {
	if x != nil {
		return x.CurrentLongitude
	}
	return 0
}

type CreateOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CustomerId        string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PickupLatitude    float64                `protobuf:"fixed64,2,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	PickupLongitude   float64                `protobuf:"fixed64,3,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	DeliveryLatitude  float64                `protobuf:"fixed64,4,opt,name=delivery_latitude,json=deliveryLatitude,proto3" json:"delivery_latitude,omitempty"`
	DeliveryLongitude float64                `protobuf:"fixed64,5,opt,name=delivery_longitude,json=deliveryLongitude,proto3" json:"delivery_longitude,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_pkg_api_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetPickupLatitude() float64 {
	if x != nil {
		return x.PickupLatitude
	}
	return 0
}

func (x *CreateOrderRequest) GetPickupLongitude() float64 {
	if x != nil {
		return x.PickupLongitude
	}
	return 0
}

func (x *CreateOrderRequest) GetDeliveryLatitude() float64 {
	if x != nil {
		return x.DeliveryLatitude
	}
	return 0
}

func (x *CreateOrderRequest) GetDeliveryLongitude() float64 {
	if x != nil {
		return x.DeliveryLongitude
	}
	return 0
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_pkg_api_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=api.OrderStatus" json:"status,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"` // Optional: used when matching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_pkg_api_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNKNOWN
}

func (x *UpdateOrderStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type StreamOrderUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderUpdatesRequest) Reset() {
	*x = StreamOrderUpdatesRequest{}
	mi := &file_pkg_api_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderUpdatesRequest) ProtoMessage() {}

func (x *StreamOrderUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamOrderUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_order_proto_rawDescGZIP(), []int{5}
}

func (x *StreamOrderUpdatesRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_pkg_api_order_proto protoreflect.FileDescriptor

const file_pkg_api_order_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/api/order.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x18DriverOrderActionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"\x9a\x04\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12'\n" +
	"\x0fpickup_latitude\x18\x04 \x01(\x01R\x0epickupLatitude\x12)\n" +
	"\x10pickup_longitude\x18\x05 \x01(\x01R\x0fpickupLongitude\x12+\n" +
	"\x11delivery_latitude\x18\x06 \x01(\x01R\x10deliveryLatitude\x12-\n" +
	"\x12delivery_longitude\x18\a \x01(\x01R\x11deliveryLongitude\x12(\n" +
	"\x06status\x18\b \x01(\x0e2\x10.api.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x122\n" +
	"\x15estimated_eta_seconds\x18\v \x01(\x01R\x13estimatedEtaSeconds\x12\x14\n" +
	"\x05price\x18\f \x01(\x01R\x05price\x12)\n" +
	"\x10current_latitude\x18\r \x01(\x01R\x0fcurrentLatitude\x12+\n" +
	"\x11current_longitude\x18\x0e \x01(\x01R\x10currentLongitude\"\xe5\x01\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12'\n" +
	"\x0fpickup_latitude\x18\x02 \x01(\x01R\x0epickupLatitude\x12)\n" +
	"\x10pickup_longitude\x18\x03 \x01(\x01R\x0fpickupLongitude\x12+\n" +
	"\x11delivery_latitude\x18\x04 \x01(\x01R\x10deliveryLatitude\x12-\n" +
	"\x12delivery_longitude\x18\x05 \x01(\x01R\x11deliveryLongitude\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"|\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.api.OrderStatusR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\"6\n" +
	"\x19StreamOrderUpdatesRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId*\xe9\x01\n" +
	"\vOrderStatus\x12\x18\n" +
	"\x14ORDER_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14ORDER_STATUS_MATCHED\x10\x02\x12\x1b\n" +
	"\x17ORDER_STATUS_PICKING_UP\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_PICKED_UP\x10\x04\x12\x1b\n" +
	"\x17ORDER_STATUS_IN_TRANSIT\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x06\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\a2\xe8\x02\n" +
	"\fOrderService\x122\n" +
	"\vCreateOrder\x12\x17.api.CreateOrderRequest\x1a\n" +
	".api.Order\x12,\n" +
	"\bGetOrder\x12\x14.api.GetOrderRequest\x1a\n" +
	".api.Order\x12>\n" +
	"\x11UpdateOrderStatus\x12\x1d.api.UpdateOrderStatusRequest\x1a\n" +
	".api.Order\x12B\n" +
	"\x12StreamOrderUpdates\x12\x1e.api.StreamOrderUpdatesRequest\x1a\n" +
	".api.Order0\x01\x128\n" +
	"\vAcceptOrder\x12\x1d.api.DriverOrderActionRequest\x1a\n" +
	".api.Order\x128\n" +
	"\vRejectOrder\x12\x1d.api.DriverOrderActionRequest\x1a\n" +
	".api.OrderB-Z+github.com/ayush/logistics-platform/pkg/apib\x06proto3"

var (
	file_pkg_api_order_proto_rawDescOnce sync.Once
	file_pkg_api_order_proto_rawDescData []byte
)

func file_pkg_api_order_proto_rawDescGZIP() []byte {
	file_pkg_api_order_proto_rawDescOnce.Do(func() {
		file_pkg_api_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_order_proto_rawDesc), len(file_pkg_api_order_proto_rawDesc)))
	})
	return file_pkg_api_order_proto_rawDescData
}

var file_pkg_api_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_order_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_api_order_proto_goTypes = []any{
	(OrderStatus)(0),                  // 0: api.OrderStatus
	(*DriverOrderActionRequest)(nil),  // 1: api.DriverOrderActionRequest
	(*Order)(nil),                     // 2: api.Order
	(*CreateOrderRequest)(nil),        // 3: api.CreateOrderRequest
	(*GetOrderRequest)(nil),           // 4: api.GetOrderRequest
	(*UpdateOrderStatusRequest)(nil),  // 5: api.UpdateOrderStatusRequest
	(*StreamOrderUpdatesRequest)(nil), // 6: api.StreamOrderUpdatesRequest
}
var file_pkg_api_order_proto_depIdxs = []int32{
	0, // 0: api.Order.status:type_name -> api.OrderStatus
	0, // 1: api.UpdateOrderStatusRequest.status:type_name -> api.OrderStatus
	3, // 2: api.OrderService.CreateOrder:input_type -> api.CreateOrderRequest
	4, // 3: api.OrderService.GetOrder:input_type -> api.GetOrderRequest
	5, // 4: api.OrderService.UpdateOrderStatus:input_type -> api.UpdateOrderStatusRequest
	6, // 5: api.OrderService.StreamOrderUpdates:input_type -> api.StreamOrderUpdatesRequest
	1, // 6: api.OrderService.AcceptOrder:input_type -> api.DriverOrderActionRequest
	1, // 7: api.OrderService.RejectOrder:input_type -> api.DriverOrderActionRequest
	2, // 8: api.OrderService.CreateOrder:output_type -> api.Order
	2, // 9: api.OrderService.GetOrder:output_type -> api.Order
	2, // 10: api.OrderService.UpdateOrderStatus:output_type -> api.Order
	2, // 11: api.OrderService.StreamOrderUpdates:output_type -> api.Order
	2, // 12: api.OrderService.AcceptOrder:output_type -> api.Order
	2, // 13: api.OrderService.RejectOrder:output_type -> api.Order
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_order_proto_init() }
func file_pkg_api_order_proto_init() {
	if File_pkg_api_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_order_proto_rawDesc), len(file_pkg_api_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_order_proto_goTypes,
		DependencyIndexes: file_pkg_api_order_proto_depIdxs,
		EnumInfos:         file_pkg_api_order_proto_enumTypes,
		MessageInfos:      file_pkg_api_order_proto_msgTypes,
	}.Build()
	File_pkg_api_order_proto = out.File
	file_pkg_api_order_proto_goTypes = nil
	file_pkg_api_order_proto_depIdxs = nil
}
